import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  // angle 5 degrees on hove
  const linkStyle =
    "flex w-full flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 text-center hover:scale-105 transition-transform duration-200 hover:rotate-1";
  const h3Style = "text-2xl font-medium";

  const ClickThrough = ({
    href,
    innerText,
    titleText,
  }: {
    href: string;
    innerText: string;
    titleText: string;
  }) => {
    return (
      <Link
        className="w-fit 
              cursor-pointer 
              underline 
              transition-all 
              decoration-1	
              duration-500 
              hover:rounded-lg
              hover:bg-sky-600
              hover:px-2
              hover:py-1
              hover:text-black
              hover:no-underline" //hover:bg-gradient-to-t from-sky-500 hover:transition-all
        href={href}
        title={titleText}
      >
        {innerText}
      </Link>
    );
  };

  return (
    <>
      <Head>
        <title>Rox.codes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center px-4 py-8 ">
          {/* picture of roxcodes on github */}
          <Image
            src="https://github.com/roxworks.png"
            alt="Picture of the author"
            width={100}
            height={100}
            className="rounded-full"
          />
          <h1 className="mb-4 text-2xl font-extrabold tracking-tight text-white">
            <span className="text-[hsl(280,100%,70%)]">Rox.codes</span>
          </h1>
          <div className="w-full flex flex-col gap-2 text-center text-[6vw] md:text-2xl text-white lg:w-3/5">
            <div>
              <span>Hey! I'm Rox. </span>
            </div>
            <div>
              <ClickThrough
                href="/projects"
                innerText="I make cool stuff for creators."
                titleText="See my projects"
              />
            </div>
            <div>
              <span>I've worked for </span>
              <ClickThrough
                href="/experience"
                innerText="MrBeast, Facebook, Microsoft"
                titleText="See my work experience"
              />
              <span>, and many others. </span>
            </div>
            <div>
              <span>Now, </span>
              <ClickThrough
                href="/workwithme"
                innerText="I help big creators start software businesses."
                titleText="Work with me"
              />
            </div>
            <div>
              <span>
                I make{" "}
                <ClickThrough
                  href="https://linktr.ee/roxcodes"
                  innerText="content"
                  titleText="My Content Links"
                />{" "}
                about what I build.{" "}
              </span>{" "}
            </div>
            <div>
              <ClickThrough
                href="/story"
                innerText="I'm trying to live the most amazing life I can."
                titleText="My Life Story"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
